vim.opt.mouse = ""
vim.opt.guicursor = "a:block,n:block-Cursor-blinkon0,i:block-iCursor-blinkon0,r:block-rCursor-blinkon0"
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.showmode = true
vim.opt.cmdheight = 0
vim.opt.laststatus = 0
vim.opt.breakindent = true
vim.opt.undofile = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.signcolumn = "yes"
vim.opt.updatetime = 550
vim.opt.timeoutlen = 550
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.list = false
vim.opt.inccommand = "split"
vim.opt.cursorline = true
vim.opt.scrolloff = 10
vim.opt.confirm = true
vim.opt.clipboard = "unnamedplus"
vim.opt.expandtab = true -- Использовать пробелы вместо табов
vim.opt.tabstop = 2 -- Визуально таб как 2 пробела
vim.opt.softtabstop = 2 -- Вставлять 2 пробела при нажатии Tab
vim.opt.shiftwidth = 2 -- Автоотступ в 2 пробела
