vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalNC", { bg = "none" })
vim.opt.mouse = ""
vim.opt.guicursor = "a:block,n:block-Cursor-blinkon0,i:block-iCursor-blinkon0,r:block-rCursor-blinkon0"
vim.opt.number = true
vim.opt.cmdheight = 0
vim.opt.relativenumber = true
vim.opt.showmode = false
vim.opt.breakindent = true
vim.opt.undofile = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.signcolumn = "yes"
vim.opt.updatetime = 550
vim.opt.timeoutlen = 550
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.list = false
vim.opt.inccommand = "split"
vim.opt.cursorline = true
vim.opt.scrolloff = 10
vim.opt.confirm = true
vim.opt.spell = true
vim.opt.spelllang = "en_us"
vim.opt.spelloptions:append("camel")
